In [ ]:
import pandas as pd
import numpy as np

### 데이터 불러오기

In [ ]:
organs = pd.read_csv("cyc_or.csv")

In [ ]:
results = pd.read_csv("cyc_re.csv")

<ipython-input-4-483ce1ee3964>:1: DtypeWarning: Columns (14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  r = pd.read_csv("cyc_re.csv")

### 날짜 기준으로 묶어 데이터 개수 확인

In [ ]:
grouped = organs.groupby('RACE_DE')

In [ ]:
for group_name, group_data in grouped:
    print(f'그룹 {group_name}:')
    print(group_data)

In [ ]:
group_counts = grouped['RACE_DE'].count()
group_counts

RACE_DE
2018.10.26    105
2018.10.27    105
2018.10.28    105
2018.11.02    105
2018.11.03    105
2018.11.04    105
2018.11.09    106
2018.11.10    106
2018.11.11    106
2018.11.16    105
2018.11.17    105
2018.11.18    105
2018.11.23    106
2018.11.24    106
2018.11.25    106
2018.11.30    105
2018.12.01    105
2018.12.02    105
2018.12.07    105
2018.12.08    105
2018.12.09    105
2018.12.14    105
2018.12.15    105
2018.12.16    105
2018.12.21    126
2018.12.22    126
2018.12.23    126
2018.12.28    127
2018.12.29    127
2018.12.30    127
2019.07.05    105
2019.07.06    105
2019.07.07    112
2019.07.12     84
2019.07.13     84
2019.07.14     91
2019.07.19    105
2019.07.20    105
2019.07.21    112
2019.07.26    105
2019.07.27    105
2019.07.28    112
2019.08.02    105
2019.08.03    105
2019.08.04    112
2019.08.09    105
2019.08.10    105
2019.08.11    112
2019.08.16    105
2019.08.17    105
2019.08.18    112
2019.08.23    105
2019.08.24    105
2019.08.25    112
2019.08.30    105
2019.08.31    105
2019.09.01    112
2019.09.06    105
2019.09.07    105
2019.09.08    105
2019.09.20    105
2019.09.21    105
2019.09.22    105
2019.09.27    105
2019.09.28    105
2019.09.29    105
2019.10.04    105
2019.10.05    105
2019.10.06    105
2019.10.11    126
2019.10.12    126
2019.10.13    126
2019.10.18    126
2019.10.19    126
2019.10.20    126
2019.10.25    126
2019.10.26    126
2019.10.27    126
2019.11.01    126
2019.11.02    126
2019.11.03    126
2019.11.08    119
2019.11.09    119
2019.11.10    119
2019.11.15    119
2019.11.16    119
2019.11.17    119
2019.11.22    119
2019.11.23    119
2019.11.24    119
2019.11.29    119
2019.11.30    119
2019.12.01    119
2019.12.06    119
2019.12.07    119
2019.12.08    119
2019.12.13    119
2019.12.14    119
2019.12.15    119
2019.12.20    119
2019.12.21    119
2019.12.22    119
2019.12.27    119
2019.12.28    119
2019.12.29    119
2020.01.03    105
2020.01.04    105
2020.01.05    105
2020.01.10    105
2020.01.11    105
2020.01.12    105
2020.01.17    105
2020.01.18    105
2020.01.19    105
2020.01.26    105
2020.01.27    105
2020.01.31    105
2020.02.01    105
2020.02.02    105
2020.02.07    105
2020.02.08    105
2020.02.09    105
2020.02.14    105
2020.02.15    105
2020.02.16    105
2020.02.21    105
2020.02.22    105
2020.10.30     42
2020.10.31     42
2020.11.01     42
2020.11.06     42
2020.11.07     42
2020.11.08     42
2020.11.13     42
2020.11.14     42
2020.11.15     42
2020.11.20     42
2020.11.21     42
2020.11.22     42
2021.02.19     42
2021.02.20     42
2021.02.21     42
2021.02.26     42
2021.02.27     42
2021.02.28     42
2021.03.05     42
2021.03.06     42
2021.03.07     42
2021.03.12     42
2021.03.13     42
2021.03.14     42
2021.03.19     42
2021.03.20     42
2021.03.21     42
2021.03.26     42
2021.03.27     42
2021.03.28     42
2021.04.02     42
2021.04.03     42
2021.04.04     42
2021.04.09     42
2021.04.10     42
2021.04.11     42
2021.05.28     42
2021.05.29     42
2021.05.30     42
2021.06.04     42
2021.06.05     42
2021.06.06     42
2021.06.11     42
2021.06.12     42
2021.06.13     42
2021.06.18     42
2021.06.19     42
2021.06.20     42
2021.06.25     42
2021.06.26     42
2021.06.27     42
2021.07.02     63
2021.07.03     63
2021.07.04     63
2021.07.09     42
2021.07.10     42
2021.07.11     42
2021.07.16     42
2021.07.17     42
2021.07.18     42
2021.07.23     42
2021.07.24     42
2021.07.25     42
2021.07.30     42
2021.07.31     42
2021.08.01     42
2021.08.06     42
2021.08.07     42
2021.08.08     42
2021.08.13     42
2021.08.14     42
2021.08.15     42
2021.08.20     42
2021.08.21     42
2021.08.22     42
2021.08.27     42
2021.08.28     42
2021.08.29     42
2021.09.03     42
2021.09.04     42
2021.09.05     42
2021.09.10     42
2021.09.11     42
2021.09.12     42
2021.09.17     42
2021.09.18     42
2021.09.19     42
2021.09.24     42
2021.09.25     42
2021.09.26     42
2021.10.01     42
2021.10.02     42
2021.10.03     42
2021.10.04     42
2021.10.08     42
2021.10.09     42
2021.10.10     42
2021.10.11     42
2021.10.15     42
2021.10.16     42
2021.10.17     42
2021.10.22     42
2021.10.23     42
2021.10.24     42
2021.10.29     42
2021.10.30     42
2021.10.31     42
2021.11.05     49
2021.11.06     49
2021.11.07     49
2021.11.12     49
2021.11.13     49
2021.11.14     49
2021.11.19     49
2021.11.20     49
2021.11.21     49
2021.11.26     63
2021.11.27     63
2021.11.28     63
2021.12.03     63
2021.12.04     63
2021.12.05     63
2021.12.10     63
2021.12.11     63
2021.12.12     63
2021.12.17     63
2021.12.18     63
2021.12.19     63
2021.12.24     84
2021.12.25     84
2021.12.26     84
2022.01.07    105
2022.01.08    105
2022.01.09    105
2022.01.14    105
2022.01.15    105
2022.01.16    105
2022.01.21    105
2022.01.22    105
2022.01.23    105
2022.01.28    105
2022.01.29    105
2022.01.30    105
2022.02.04    105
2022.02.05    105
2022.02.06    105
2022.02.11    105
2022.02.12    105
2022.02.13    105
2022.02.18    105
2022.02.19    105
2022.02.20    105
2022.02.25    105
2022.02.26    105
2022.02.27    105
2022.03.04    105
2022.03.05    105
2022.03.06    105
2022.03.11     84
2022.03.12     84
2022.03.13     84
2022.03.18     84
2022.03.19     84
2022.03.20     84
2022.03.25     84
2022.03.26     84
2022.03.27     84
2022.04.01    105
2022.04.02    105
2022.04.03    105
2022.04.08    105
2022.04.09    105
2022.04.10    105
2022.04.15    105
2022.04.16    105
2022.04.17    105
2022.04.22    105
2022.04.23    105
2022.04.24    105
2022.04.29    105
2022.04.30    105
2022.05.01    105
2022.05.06    105
2022.05.07    105
2022.05.08    105
2022.05.13    105
2022.05.14    105
2022.05.15    105
2022.05.20    105
2022.05.21    105
2022.05.22    105
2022.05.27    105
2022.05.28    105
2022.05.29    105
2022.06.03    105
2022.06.04    105
2022.06.05    105
2022.06.10    112
2022.06.11    112
2022.06.12    112
2022.06.17    112
2022.06.18    112
2022.06.19    112
2022.06.24    112
2022.06.25    112
2022.06.26    112
2022.07.01    112
2022.07.02    112
2022.07.03    112
2022.07.08    112
2022.07.09    112
2022.07.10    112
2022.07.15    112
2022.07.16    112
2022.07.17    112
2022.07.22    112
2022.07.23    112
2022.07.24    112
2022.07.29    112
2022.07.30    112
2022.07.31    112
2022.08.05    112
2022.08.06    112
2022.08.07    112
2022.08.12    112
2022.08.13    112
2022.08.14    112
2022.08.15    112
2022.08.19    112
2022.08.20    112
2022.08.21    112
2022.08.26    112
2022.08.27    112
2022.08.28    112
2022.09.02    112
2022.09.03    112
2022.09.04    112
2022.09.11    112
2022.09.12    112
2022.09.16    112
2022.09.17    112
2022.09.18    112
2022.09.23    112
2022.09.24    112
2022.09.25    112
2022.09.30    112
2022.10.01    112
2022.10.02    112
2022.10.03    112
2022.10.07    112
2022.10.08    112
2022.10.09    112
2022.10.14    112
2022.10.15    112
2022.10.16    112
2022.10.21    112
2022.10.22    112
2022.10.23    112
2022.10.28    112
2022.10.29    112
2022.10.30    112
2022.11.04    112
2022.11.05    112
2022.11.06    112
2022.11.11    112
2022.11.12    112
2022.11.13    112
2022.11.18    112
2022.11.19    112
2022.11.20    112
2022.11.25    112
2022.11.26    112
2022.11.27    112
2022.12.02    112
2022.12.03    112
2022.12.04    112
2022.12.09    112
2022.12.10    112
2022.12.11    112
2022.12.16    112
2022.12.17    112
2022.12.18    112
2022.12.23    112
2022.12.24    112
2022.12.25    112
2022.12.30    112
2023.01.06    112
2023.01.07    112
2023.01.08    112
2023.01.13    112
2023.01.14    112
2023.01.15    112
2023.01.20    112
2023.01.21    112
2023.01.27    112
2023.01.28    112
2023.01.29    112
2023.02.03    112
2023.02.04    112
2023.02.05    112
2023.02.10    112
2023.02.11    112
2023.02.12    112
2023.02.17    112
2023.02.18    112
2023.02.19    112
2023.02.24    112
2023.02.25    112
2023.02.26    112
2023.03.03    112
2023.03.04    112
2023.03.05    112
2023.03.10    112
2023.03.11    112
2023.03.12    112
2023.03.17    112
2023.03.18    112
2023.03.19    112
2023.03.24    112
2023.03.25    112
2023.03.26    112
2023.03.31    112
Name: RACE_DE, dtype: int64

In [ ]:
# 누락없이 전체 출력 옵션

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
grouped1 = results.groupby(['BASE_YEAR', 'RACE_DE'])
group_sizes1 = grouped1.size()

print(group_sizes1)

BASE_YEAR  RACE_DE
2018       1026       105
           1027       105
           1028       105
           1102       105
           1103       105
           1104       105
           1109       105
           1110       105
           1111       105
           1116       105
           1117       105
           1118       105
           1123       105
           1124       105
           1125       105
           1130       105
           1201       105
           1202       105
           1207       105
           1208       105
           1209       105
           1214       105
           1215       105
           1216       105
           1221       126
           1222       126
           1223       126
           1228       126
           1229       126
           1230       126
2019       705        105
           706        105
           707        112
           712         84
           713         84
           714         91
           719        105
           720        105
           721        112
           726        105
           727        105
           728        112
           802        105
           803        105
           804        112
           809        105
           810        105
           811        112
           816        105
           817        105
           818        112
           823        105
           824        105
           825        112
           830        105
           831        105
           901        112
           906        105
           907        105
           908        105
           920        105
           921        105
           922        105
           927        105
           928        105
           929        105
           1004       105
           1005       105
           1006       105
           1011       126
           1012       126
           1013       126
           1018       126
           1019       126
           1020       126
           1025       126
           1026       126
           1027       126
           1101       126
           1102       126
           1103       126
           1108       119
           1109       119
           1110       119
           1115       119
           1116       119
           1117       119
           1122       119
           1123       119
           1124       119
           1129       119
           1130       119
           1201       119
           1206       119
           1207       119
           1208       119
           1213       119
           1214       119
           1215       119
           1220       119
           1221       119
           1222       119
           1227       119
           1228       119
           1229       119
2020       103        105
           104        105
           105        105
           110        105
           111        105
           112        105
           117        105
           118        105
           119        105
           126        105
           127        105
           131        105
           201        105
           202        105
           207        105
           208        105
           209        105
           214        105
           215        105
           216        105
           221        105
           222        105
           1030        42
           1031        42
           1101        42
           1106        42
           1107        42
           1108        42
           1113        42
           1114        42
           1115        42
           1120        42
           1121        42
           1122        42
2021       219         42
           220         42
           221         42
           226         42
           227         42
           228         42
           305         42
           306         42
           307         42
           312         42
           313         42
           314         42
           319         42
           320         42
           321         42
           326         42
           327         42
           328         42
           402         42
           403         42
           404         42
           409         42
           410         42
           411         42
           528         42
           529         42
           530         42
           604         42
           605         42
           606         42
           611         42
           612         42
           613         42
           618         42
           619         42
           620         42
           625         42
           626         42
           627         42
           702         63
           703         63
           704         63
           709         42
           710         42
           711         42
           716         42
           717         42
           718         42
           723         42
           724         42
           725         42
           730         42
           731         42
           801         42
           806         42
           807         42
           808         42
           813         42
           814         42
           815         42
           820         42
           821         42
           822         42
           827         42
           828         42
           829         42
           903         42
           904         42
           905         42
           910         42
           911         42
           912         42
           917         42
           918         42
           919         42
           924         42
           925         42
           926         42
           1001        42
           1002        42
           1003        42
           1004        42
           1008        42
           1009        42
           1010        42
           1011        42
           1015        42
           1016        42
           1017        42
           1022        42
           1023        42
           1024        42
           1029        42
           1030        42
           1031        42
           1105        49
           1106        49
           1107        49
           1112        49
           1113        49
           1114        49
           1119        49
           1120        49
           1121        49
           1126        63
           1127        63
           1128        63
           1203        63
           1204        63
           1205        63
           1210        63
           1211        63
           1212        63
           1217        63
           1218        63
           1219        63
           1224        84
           1225        84
           1226        84
2022       107        105
           108        105
           109        105
           114        105
           115        105
           116        105
           121        105
           122        105
           123        105
           128        105
           129        105
           130        105
           204        105
           205        105
           206        105
           211        105
           212        105
           213        105
           218        105
           219        105
           220        105
           225        105
           226        105
           227        105
           304        105
           305        105
           306        105
           311         84
           312         84
           313         84
           318         84
           319         84
           320         84
           325         84
           326         84
           327         84
           401        105
           402        105
           403        105
           408        105
           409        105
           410        105
           415        105
           416        105
           417        105
           422        105
           423        105
           424        105
           429        105
           430        105
           501        105
           506        105
           507        105
           508        105
           513        105
           514        105
           515        105
           520        105
           521        105
           522        105
           527        105
           528        105
           529        105
           603        105
           604        105
           605        105
           610        112
           611        112
           612        112
           617        112
           618        112
           619        112
           624        112
           625        112
           626        112
           701        112
           702        112
           703        112
           708        112
           709        112
           710        112
           715        112
           716        112
           717        112
           722        112
           723        112
           724        112
           729        112
           730        112
           731        112
           805        112
           806        112
           807        112
           812        112
           813        112
           814        112
           815        112
           819        112
           820        112
           821        112
           826        112
           827        112
           828        112
           902        112
           903        112
           904        112
           911        112
           912        112
           916        112
           917        112
           918        112
           923        112
           924        112
           925        112
           930        112
           1001       112
           1002       112
           1003       112
           1007       112
           1008       112
           1009       112
           1014       112
           1015       112
           1016       112
           1021       112
           1022       112
           1023       112
           1028       112
           1029       112
           1030       112
           1104       112
           1105       112
           1106       112
           1111       112
           1112       112
           1113       112
           1118       112
           1119       112
           1120       112
           1125       112
           1126       112
           1127       112
           1202       112
           1203       112
           1204       112
           1209       112
           1210       112
           1211       112
           1216       112
           1217       112
           1218       112
           1223       112
           1224       112
           1225       112
           1230       112
2023       106        112
           107        112
           108        112
           113        112
           114        112
           115        112
           120        112
           121        112
           127        112
           128        112
           129        112
           203        112
           204        112
           205        112
           210        112
           211        112
           212        112
           217        112
           218        112
           219        112
           224        112
           225        112
           226        112
           303        112
           304        112
           305        112
           310        112
           311        112
           312        112
           317        112
           318        112
           319        112
           324        112
           325        112
           326        112
           331        112
dtype: int64

In [ ]:
import pandas as pd
# 중복된 행 제거
organs = organs.drop_duplicates()

### 데이터 개수 맞추고 등수 컬럼 "result" 추가

In [ ]:
### 컬럼 이름을 사용하여 포함 여부 판별하는 함수 생성 ###
def is_value_in_column(row, a_col, b_col, c_col, d_col):
    a_val = str(row[a_col])  # 숫자 데이터를 문자열로 변환
    b_val = str(row[b_col])
    c_val = str(row[c_col])
    d_val = str(row[d_col])

    if any(val in b_val for val in a_val.split()):
        return 1
    elif any(val in c_val for val in a_val.split()):
        return 2
    elif any(val in d_val for val in a_val.split()):
        return 3
    else:
        return 0


organs['result'] = organs.apply(is_value_in_column, args=('PLAYER_NM', 'N1R_PLAYER_NM', 'N2R_PLAYER_NM', 'N3R_PLAYER_NM'), axis=1)

print(organs)

      OPER_INSTT_NM  BASE_YEAR  TME_VALUE  DAY_ORD_VALUE     RACE_DE  RACE_NO  \
0              광명         2023         13              1  2023.03.31        1
1              광명         2023         13              1  2023.03.31        1
2              광명         2023         13              1  2023.03.31        1
3              광명         2023         13              1  2023.03.31        1
4              광명         2023         13              1  2023.03.31        1
...             ...        ...        ...            ...         ...      ...
40791          광명         2018         42              1  2018.10.26       15
40792          광명         2018         42              1  2018.10.26       15
40793          광명         2018         42              1  2018.10.26       15
40794          광명         2018         42              1  2018.10.26       15
40795          광명         2018         42              1  2018.10.26       15

       BACK_NO COLOR_NM PLAYER_NM  AGE_CO  ...  WNPZ_TCTCS_OVRTK_NCNT  \
0            1        백       박경태      40  ...                      0
1            2        흑       유진용      50  ...                      3
2            3        적       유연종      39  ...                      6
3            4        청       강철호      41  ...                      0
4            5        황       신우삼      49  ...                      6
...        ...      ...       ...     ...  ...                    ...
40791        3        적       김종력      35  ...                      1
40792        4        청       김동관      33  ...                      2
40793        5        황       이정우      30  ...                      4
40794        6        녹       박건비      31  ...                     11
40795        7       분홍       박병하      37  ...                      9

       WNPZ_TCTCS_DEFNS_NCNT  GRAD_MDAT_CURNT_NM GRAD_MDAT_BEFORE_NM  \
0                          2                   1                 1.0
1                          3                   1                 1.0
2                          4                   1                 1.0
3                          6                   1                 1.0
4                         15                   1                 1.0
...                      ...                 ...                 ...
40791                      9                   3                 3.0
40792                      5                   3                 3.0
40793                     10                   3                 3.0
40794                     17                   3                 3.0
40795                      3                   3                 3.0

       AVRG_GTSR_TMS3_VALUE  AVRG_GTSR_GNRLZ_VALUE  N1R_PLAYER_NM  \
0                    84.229                 84.300           ⑦이기한
1                    85.569                 85.043           ⑦이기한
2                    87.759                 88.282           ⑦이기한
3                    85.431                 83.984           ⑦이기한
4                    86.063                 86.383           ⑦이기한
...                     ...                    ...            ...
40791                97.641                 97.641           ①정종진
40792                97.883                 97.883           ①정종진
40793                98.439                 98.753           ①정종진
40794                99.178                 99.178           ①정종진
40795               101.217                101.217           ①정종진

       N2R_PLAYER_NM  N3R_PLAYER_NM  result
0               ⑥심상훈           ③유연종       0
1               ⑥심상훈           ③유연종       0
2               ⑥심상훈           ③유연종       3
3               ⑥심상훈           ③유연종       0
4               ⑥심상훈           ③유연종       0
...              ...            ...     ...
40791           ⑦박병하           ②최래선       0
40792           ⑦박병하           ②최래선       0
40793           ⑦박병하           ②최래선       0
40794           ⑦박병하           ②최래선       0
40795           ⑦박병하           ②최래선       2

[40796 rows x 28 columns]

In [ ]:
organs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40796 entries, 0 to 40795
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   OPER_INSTT_NM          40796 non-null  object
 1   BASE_YEAR              40796 non-null  int64
 2   TME_VALUE              40796 non-null  int64
 3   DAY_ORD_VALUE          40796 non-null  int64
 4   RACE_DE                40796 non-null  object
 5   RACE_NO                40796 non-null  int64
 6   BACK_NO                40796 non-null  int64
 7   COLOR_NM               40796 non-null  object
 8   PLAYER_NM              40796 non-null  object
 9   AGE_CO                 40796 non-null  int64
 10  VICTRY_RT              40796 non-null  int64
 11  YUNDAE_RT              40796 non-null  int64
 12  THREE_YUNDAE_RT        40796 non-null  int64
 13  GRAD_MDAT_CURNT_NM     40796 non-null  int64
 14  GRAD_MDAT_BEFORE_NM    40506 non-null  float64
 15  AVRG_GTSR_TMS3_VALUE   40796 non-null  float64
 16  AVRG_GTSR_GNRLZ_VALUE  40796 non-null  float64
 17  N1R_PLAYER_NM          40796 non-null  object
 18  N2R_PLAYER_NM          40565 non-null  object
 19  N3R_PLAYER_NM          40446 non-null  object
 20  result                 40796 non-null  int64
dtypes: float64(3), int64(11), object(7)
memory usage: 6.5+ MB

In [ ]:
# [이전등급]의 NaN 값을 [현재등급]으로 채우기
organs['GRAD_MDAT_BEFORE_NM'].fillna(organs['GRAD_MDAT_CURNT_NM'], inplace=True)

In [ ]:
drop = ['WNPZ_NCNT',	'RACE_PARTCPT_NCNT',	'WNPZ_TCTCS_PRECDNG_NCNT',	'WNPZ_TCTCS_EXCD_NCNT',	'WNPZ_TCTCS_OVRTK_NCNT',	'WNPZ_TCTCS_DEFNS_NCNT', 'PLAYER_GRAD_NM']

o.drop(drop, axis=1, inplace=True)

In [ ]:
drop = ['N3R_PLAYER_NM','N2R_PLAYER_NM', 'N1R_PLAYER_NM']

o.drop(drop, axis=1, inplace=True)

In [ ]:
# NaN 값을 가지는 행만 출력
nan_rows = o[o.isna().any(axis=1)]

nan_rows

# Nulll 값 없는 거 확인

Empty DataFrame
Columns: [OPER_INSTT_NM, BASE_YEAR, TME_VALUE, DAY_ORD_VALUE, RACE_DE, RACE_NO, BACK_NO, COLOR_NM, PLAYER_NM, AGE_CO, VICTRY_RT, YUNDAE_RT, THREE_YUNDAE_RT, GRAD_MDAT_CURNT_NM, GRAD_MDAT_BEFORE_NM, AVRG_GTSR_TMS3_VALUE, AVRG_GTSR_GNRLZ_VALUE, result]
Index: []

In [ ]:
o.head()

,OPER_INSTT_NM,BASE_YEAR,TME_VALUE,DAY_ORD_VALUE,RACE_DE,RACE_NO,BACK_NO,COLOR_NM,PLAYER_NM,AGE_CO,...,YUNDAE_RT,THREE_YUNDAE_RT,GRAD_MDAT_CURNT_NM,GRAD_MDAT_BEFORE_NM,AVRG_GTSR_TMS3_VALUE,AVRG_GTSR_GNRLZ_VALUE,N1R_PLAYER_NM,N2R_PLAYER_NM,N3R_PLAYER_NM,result
0,광명,2023,13,1,2023.03.31,1,1,백,박경태,40,...,0,0,1,1.0,84.229,84.300,⑦이기한,⑥심상훈,③유연종,5.5
1,광명,2023,13,1,2023.03.31,1,2,흑,유진용,50,...,0,20,1,1.0,85.569,85.043,⑦이기한,⑥심상훈,③유연종,5.5
2,광명,2023,13,1,2023.03.31,1,3,적,유연종,39,...,57,71,1,1.0,87.759,88.282,⑦이기한,⑥심상훈,③유연종,3.0
3,광명,2023,13,1,2023.03.31,1,4,청,강철호,41,...,0,0,1,1.0,85.431,83.984,⑦이기한,⑥심상훈,③유연종,5.5
4,광명,2023,13,1,2023.03.31,1,5,황,신우삼,49,...,40,40,1,1.0,86.063,86.383,⑦이기한,⑥심상훈,③유연종,5.5

In [ ]:
# 전처리 후 새로운 파일('new.csv')로 저장
o.to_csv('new.csv', index=False, encoding='utf-8-sig')